### ISSUE TITLE
Debug packages

### ISSUE THREAD

**Issue by mrzor** [kelleyk/ppa-emacs#10]
Thanks for making the builds and help me get fresh Emacs ! It is very much appreciated.

Do you think it would be doable to build a `-dbg` package alongside the normal builds ? I'm not sure what's involved in that endeavor.

Cheers !

**Comment by kelleyk** [comment]
They should be available, actually!  Have you seen this section of the [PPA readme](https://launchpad.net/~kelleyk/+archive/ubuntu/emacs)?

> Debug symbols are available! After adding the PPA however you normally do, find the corresponding entry in `/etc/apt/sources.list.d`.
> It will look like the first line below (though the suite name may be different if you are not using bionic); duplicate it and change the component name ("main") to "main/debug".
>   deb http://ppa.launchpad.net/kelleyk/emacs/ubuntu bionic main
>   deb http://ppa.launchpad.net/kelleyk/emacs/ubuntu bionic main/debug

Please feel free to reopen this issue if you have any trouble!
