### ISSUE TITLE
Backport packaging changes to Emacs 26.x?

### ISSUE THREAD

**Issue by kelleyk** [kelleyk/ppa-emacs#13]
As described in #1, #3, #4, #11, etc., there have been a few rough edges with the packaging that should now be resolved for the `emacs27` packages.

I'm considering whether or not to backport those changes to 26.x and would appreciate input from anyone with an opinion.  In particular, the `load-path` changes will mean that anyone who was taking advantage of the old behavior will see a change.

**Comment by alphapapa** [comment]
Is there any way for you to get download stats for those older versions?  I wonder how many people are still installing them.  (On the other hand, if someone is staying on an older version, they might not have downloaded it for a long time, but they might still receive an update if one were published.)

If I were you, I'd not bother unless someone needs it.  If they've been dealing with it for this long, they probably don't need the changes.

**Comment by kelleyk** [comment]
I did get download stats and decided not to bother because usage was so low.  At this point, I think the issue can be safely closed!
