### ISSUE TITLE
Emacs from your repository does not scale properly on my high dpi display?

### ISSUE THREAD

**Issue by simurgh9** [kelleyk/ppa-emacs#17]
I asked this [question](https://emacs.stackexchange.com/questions/64185/emacs-not-being-scaled-properly), please take a look. When I install emacs from your ppa, I get a really small scaled window but the emacs from Ubuntu's own ppa (Emacs 26) looks fine. There are pictures in the link I provided.

**Comment by kelleyk** [comment]
Hello!  I'm sorry that you're having trouble.  Emacs 27 behaves a little bit differently than Emacs 26 does in high-DPI situations.

I use Emacs (from my PPA) in a high-DPI environment without any trouble, which suggests that there might be something different about your desktop environment.

Unfortunately, I only package Emacs.  I wish I could be more helpful!

**Comment by simurgh9** [comment]
Could we compare desktop environments and variables in hopes of fixing my rendering of Emacs?
