### ISSUE TITLE
Emacs 28.1

### ISSUE THREAD

**Issue by avishefi** [kelleyk/ppa-emacs#21]
Any plan on releasing Emacs 28.1 to the PPA?

**Comment by zabbal** [comment]
Neat! Would be great to see more recent Ubuntu releases as well.

**Comment by kelleyk** [comment]
Take a look and let me know what you think!  I've uploaded 28.1 to the PPA and included builds for 21.10 ("impish") and 22.04 LTS ("jammy").

There are release notes at https://github.com/kelleyk/ppa-emacs/.

**Comment by pataquets** [comment]
A million thanks, @kelleyk!
So far, I've confirmed #24, adding my workaround and filed #25 with some links, in case someone has better understanding than me to make it happen.
You are awesome!

**Comment by avishefi** [comment]
Thanks @kelleyk !
