### ISSUE TITLE
ctrl-h i: help table of contents missing 26.1

### ISSUE THREAD

**Issue by jots** [kelleyk/ppa-emacs#5]
thanks for making this ppa.  one thing: after installing it, ctrl-h i has an empty table of contents.  is there something else that needs to be done to get the help files?
I installed by:
```
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt install emacs26-nox
```

**Comment by kelleyk** [comment]
Thanks for taking the time to report this issue.  Did you ever resolve it?

If it's still a problem, what version of Ubuntu are you using?  Does starting `emacs` with `-Q` (to skip your configuration) change the behavior?

**Comment by kelleyk** [comment]
I'm going to close this issue since it has been idle for a while; feel free to reopen it if necessary.
