### ISSUE TITLE
Emacs Missing Required Script

### ISSUE THREAD

**Issue by sdrafahl** [kelleyk/ppa-emacs#6]
After installing emacs via the PPA 
`sudo apt-get install emacs26`
Then when I try running it with 
`emacs26`
I get 
```
Warning: Could not find simple.el or simple.elc
Cannot open load file: No such file or directory, warnings
```

**Comment by sdrafahl** [comment]
Turns out it was a unrelated problem.

**Comment by jia-j-chen** [comment]
How did you solve this problem?

I encountered the same error message when I did:

installing emacs27 via the PPA
sudo apt-get install emacs27
Then when I try running it with
emacs27
I get
