### ISSUE TITLE
emacs26 conflicts with emacs26-nox in 26.3~1.git96dd019-kk1+18.04 version

### ISSUE THREAD

**Issue by csrabak** [kelleyk/ppa-emacs#7]
In this version for emacs 26, an attempt to install simoutaneusly both X (GTK+) windows and text only version (nox) generates a conflict that shows in Synaptic tool.

If emacs26 is installed and attempt to add emacs26-nox via command line apt install, apt informs that emacs26 would be uninstalled first.

**Comment by kelleyk** [comment]
Thank you for taking the time to open an issue!

I believe that this is correct; if you want to be able to run Emacs both ways, you want the `emacs26` packages.  Have you tried installing that and then starting Emacs with `emacs -nw`?
