### ISSUE TITLE
PPA build failing for 26.3 on 16.04/amd64

### ISSUE THREAD

**Issue by kelleyk** [kelleyk/ppa-emacs#8]
I've tried repeating the build with the same outcome, so this doesn't seem like a transient problem.  26.2 built just fine on 16.04/amd64 (edited: I had typed "18.04/amd64"), and 26.3 builds successfully on other version/architecture combinations.

I need to dig in and figure out what's going on.

**Comment by dmusican** [comment]
Thanks for working on this, much appreciated. Though the problem I'm having with 26.3 is on Xenial, which is 16.04. Are you seeing different behavior than me, or is that just a typo in the description?

**Comment by kelleyk** [comment]
Oops: you're completely right.  I meant 16.04 (Xenial), not 18.04 (Bionic).

**Comment by CarstenKoenig** [comment]
is there any news on that?

I'm still on Xenial and emacs/melpa is basically unusable for me till I can update

**Comment by kelleyk** [comment]
@CarstenKoenig It's true that 26.3 ships with a still-valid ELPA signing key, but you can fix this issue now and quite easily!  #9 discusses the key expiration issue, and the README for the [gnu-elpa-keyring-update package](https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html) has instructions on how to add the current key to the keyring.

I have not had a chance to dig into this yet, but am hoping to have some time over the holidays to peek.

**Comment by kelleyk** [comment]
Here are some build logs:
- [https://launchpadlibrarian.net/419032022/buildlog_ubuntu-xenial-amd64.emacs26_26.2~1.gitfd1b34b-kk1+16.04_BUILDING.txt.gz](26.3 / 16.04), which fails
- [https://launchpadlibrarian.net/442881309/buildlog_ubuntu-bionic-armhf.emacs26_26.3~1.git96dd019-kk1+18.04_BUILDING.txt.gz](26.3 / 18.04), which succeeds
- [https://launchpadlibrarian.net/419031899/buildlog_ubuntu-xenial-i386.emacs26_26.2~1.gitfd1b34b-kk1+16.04_BUILDING.txt.gz](26.2 / 16.04), which succeeds

It seems that the build does actually complete, but that one of the tests runs indefinitely until it is killed after 150 minutes.  The successful builds take 10-15 minutes.

    make: *** [build] Terminated
    debian/rules:128: recipe for target 'override_dh_auto_test' failed
    make[1]: *** [override_dh_auto_test] Terminated
    Build killed with signal TERM after 150 minutes of inactivity

There are some other error messages, but none that don't appear in the successful runs as well.

I'm going to see if I can replicate locally, and if I can, there are only about 200 new commits between 26.2 and 26.3; maybe it's worth trying to bisect.

**Comment by kelleyk** [comment]
After spending several hours trying to reproduce this locally, I gave up and triggered a rebuild on Launchpad.  It seems to have worked, so 16.04 users should now see packages for Emacs 26.3.

I'm going to close this, but we'll see if there are similar problems on the next upstream release.

**Comment by dmusican** [comment]
Thank you!
