### ISSUE TITLE
ELPA signing key expired

### ISSUE THREAD

**Issue by kelleyk** [kelleyk/ppa-emacs#9]
An email from Eugene J. (thank you!) has tipped me off that a GPG key related to the PPA has apparently expired.  This apparently came up in a Gitter chat related to Spacemacs (https://gitter.im/syl20bnr/spacemacs?at=5de67bce9319bb5190d6f67d).  I haven't had a chance to investigate the actual issue yet.

[Edit:] Aha: this looks like it might be a problem with the rotation of the ELPA signing key supplied with Emacs, which broke my personal installation until I figured out how to update the key.

**Comment by JAremko** [comment]
I think it only affects Emacs 25.x  This is [how error looks](https://circleci.com/gh/syl20bnr/spacemacs/48359?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by kelleyk** [comment]
That would make sense.  The backstory here is that the keys used to sign the ELPA package indices never used to be rotated, but now are.  I'm not sure exactly which keys are shipped with which versions of Emacs or why this started breaking just now, though a signing key expired in September 2019, which could be related.

Users who are impacted will want to follow the directions in the README for the [gnu-elpa-keyring-update package](https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html) and then (once ELPA is working again for you) install that package.  As long as you're installing package updates semi-regularly, you will then get new signing keys before the old ones expire.

I _believe_ that I recall (from when this issue hit my own installation) that installing a newer version of Emacs did not actually resolve the issue, because doing that didn't blow away the existing `~/.emacs.d/elpa/gnupg` directory, which contains only the older, expired keys.

I'm not sure how to feel about updating my packages for older versions of Emacs to include newer signing keys, and I'm also not sure how difficult that will be.  I'll look into it, but comments from folks using the packages are more than welcome.

**Comment by kelleyk** [comment]
I've cherry-picked 26f9a77 onto the 25.3 branch as c09215a and pushed new `emacs25` packages.  Any Emacs 25 packages from the PPA with version `25.3~2` or later should include the new 2019 signing key, which expires in 2024.

Please let me know if there is any trouble with these new packages, since I don't personally use Emacs 25 any longer!
